version: '3'
services:
  flask_app:
    build: .
    ports:
      - "5000:5000"
    volumes:
      - .:/app
    depends_on:
      - redis
    environment:
      FLASK_APP: script.py
      CACHE_REDIS_URL: redis://redis:6379/0
      CELERY_BROKER_URL: redis://redis:6379/1
      CELERY_RESULT_BACKEND: redis://redis:6379/1
    command: flask run --host=0.0.0.0

  redis:
    image: "redis:latest"
    ports:
      - "6379:6379"