version: "3"
services:
  flask_app:
    build: .
    ports:
      - "5000:5000"
    volumes:
      - ./src:/app/src
    depends_on:
      - redis
    environment:
      FLASK_APP: src/script
      CACHE_REDIS_URL: redis://redis:6379/0
      CELERY_BROKER_URL: redis://redis:6379/1
      # CELERY_RESULT_BACKEND: redis://redis:6379/1
    command: python src/script.py

  redis:
    image: "redis:latest"
    ports:
      - "6379:6379"
